export const WMO = [
        {code: '0', text: 'Sunny', icon: '01'},
        {code: '1', text: 'Mainly Clear', icon: '02'},
        {code: '2', text: 'Partly Cloudy', icon: '02'},
        {code: '3', text: 'Overcast', icon: '03'},
        {code: '45', text: 'Fog', icon: '50'},
        {code: '48', text: 'Rime Fog', icon: '50'},
        {code: '51', text: 'Light Drizzle', icon: '09'},
        {code: '53', text: 'Moderate Drizzle', icon: '09'},
        {code: '55', text: 'Drizzle', icon: '09'},
        {code: '56', text: 'Light Freezing Drizzle', icon: '10'},
        {code: '57', text: 'Heavy Freezing Drizzle', icon: '10'},
        {code: '61', text: 'Light Rain', icon: '10'},
        {code: '63', text: 'Moderate Rain', icon: '10'},
        {code: '65', text: 'Heavy Rain', icon: '10'},
        {code: '66', text: 'Light Freezing Rain', icon: '10'},
        {code: '67', text: 'Heavy Freezing Rain', icon: '10'},
        {code: '71', text: 'Snow Flurries', icon: '13'},
        {code: '73', text: 'Snow', icon: '13'},
        {code: '75', text: 'Snow Storm', icon: '13'},
        {code: '77', text: 'Snow Grain', icon: '13'},
        {code: '80', text: 'Light Rain', icon: '09'},
        {code: '81', text: 'Rain', icon: '09'},
        {code: '82', text: 'Rain Storm', icon: '09'},
        {code: '85', text: 'Light Snow Showers', icon: '13'},
        {code: '86', text: 'Heavy Snow Showers', icon: '13'},
        {code: '95', text: 'Thunderstorm', icon: '11'},
        {code: '96', text: 'Thunderstorm/Light Hail', icon: '11'},
        {code: '99', text: 'Thunderstorm/Heavy Hai;', icon: '11'},
];
    
export const getWMOInfo = (id:string|number) =>  WMO.find(info => info.code == id )

